### ISSUE TITLE
[BUG]: Clear out inputs in the add item form after clicking OK on the alert 

### ISSUE THREAD

**Issue by deeheber** [the-collab-lab/tcl-66-smart-shopping-list#29]
I noticed when adding an item the state in the inputs (item name + time frame) arent't getting cleared out after clicking "ok" in the alert. Feels like a minor fix with clearing out that state if that's not intentional behavior.

Creating this issue so we don't forget to follow up. This originated in [ this pr comment](https://github.com/the-collab-lab/tcl-66-smart-shopping-list/pull/27#pullrequestreview-1907828024), but was unrelated to the item being pr'ed.

Looks like the component in question is in `src/components/AddItem.jsx`

This can be addressed at the end during the styling week, but if someone has time/interest feel free to assign to yourself and have at least one person approve the PR before merging.

**Comment by hun-ah** [comment]
I noticed this as well - I can fix it!

**Comment by deeheber** [comment]
Thanks @hun-ah !
